import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const columns = [
  { name: "Images", uid: "image", sortable: true },
  { name: "Room type", uid: "roomtype", sortable: true },
  { name: "Price", uid: "price", sortable: true },
  { name: "Promotion Price", uid: "PromotionPrice", sortable: true },
  { name: "Guests(s)", uid: "Guest", sortable: true },
  { name: "Bed type", uid: "bedtype" },
  { name: "Room Size", uid: "Roomsize", sortable: true },
];

const users = [
  // {
  //   image: "path/to/image1.jpg",
  //   roomtype: "Deluxe",
  //   price: "$150",
  //   PromotionPrice: "$120",
  //   Guest: 2,
  //   bedtype: "Single bed",
  //   Roomsize: "30 sqm",
  // },
  // {
  //   image: "path/to/image2.jpg",
  //   roomtype: "Deluxe",
  //   price: "$160",
  //   PromotionPrice: "$130",
  //   Guest: 2,
  //   bedtype: "Double bed",
  //   Roomsize: "32 sqm",
  // },
  // {
  //   image: "path/to/image3.jpg",
  //   roomtype: "Standard",
  //   price: "$100",
  //   PromotionPrice: "$80",
  //   Guest: 1,
  //   bedtype: "Single bed",
  //   Roomsize: "25 sqm",
  // },
  // {
  //   image: "path/to/image4.jpg",
  //   roomtype: "Standard",
  //   price: "$110",
  //   PromotionPrice: "$90",
  //   Guest: 2,
  //   bedtype: "Double bed",
  //   Roomsize: "27 sqm",
  // },
  // {
  //   image: "path/to/image5.jpg",
  //   roomtype: "Suite",
  //   price: "$200",
  //   PromotionPrice: "$180",
  //   Guest: 4,
  //   bedtype: "King bed",
  //   Roomsize: "50 sqm",
  // },
  // {
  //   image: "path/to/image6.jpg",
  //   roomtype: "Suite",
  //   price: "$220",
  //   PromotionPrice: "$200",
  //   Guest: 4,
  //   bedtype: "King bed",
  //   Roomsize: "55 sqm",
  // },
  // {
  //   image: "path/to/image7.jpg",
  //   roomtype: "Deluxe",
  //   price: "$140",
  //   PromotionPrice: "$110",
  //   Guest: 2,
  //   bedtype: "Single bed",
  //   Roomsize: "30 sqm",
  // },
  // {
  //   image: "path/to/image8.jpg",
  //   roomtype: "Deluxe",
  //   price: "$150",
  //   PromotionPrice: "$120",
  //   Guest: 2,
  //   bedtype: "Double bed",
  //   Roomsize: "32 sqm",
  // },
  // {
  //   image: "path/to/image9.jpg",
  //   roomtype: "Standard",
  //   price: "$95",
  //   PromotionPrice: "$75",
  //   Guest: 1,
  //   bedtype: "Single bed",
  //   Roomsize: "25 sqm",
  // },
  // {
  //   image: "path/to/image10.jpg",
  //   roomtype: "Standard",
  //   price: "$105",
  //   PromotionPrice: "$85",
  //   Guest: 2,
  //   bedtype: "Double bed",
  //   Roomsize: "27 sqm",
  // },
  // {
  //   image: "path/to/image11.jpg",
  //   roomtype: "Suite",
  //   price: "$210",
  //   PromotionPrice: "$190",
  //   Guest: 4,
  //   bedtype: "King bed",
  //   Roomsize: "50 sqm",
  // },
  // {
  //   image: "path/to/image12.jpg",
  //   roomtype: "Suite",
  //   price: "$230",
  //   PromotionPrice: "$210",
  //   Guest: 4,
  //   bedtype: "King bed",
  //   Roomsize: "55 sqm",
  // },
  // {
  //   image: "path/to/image13.jpg",
  //   roomtype: "Deluxe",
  //   price: "$155",
  //   PromotionPrice: "$125",
  //   Guest: 2,
  //   bedtype: "Single bed",
  //   Roomsize: "30 sqm",
  // },
  // {
  //   image: "path/to/image14.jpg",
  //   roomtype: "Deluxe",
  //   price: "$165",
  //   PromotionPrice: "$135",
  //   Guest: 2,
  //   bedtype: "Double bed",
  //   Roomsize: "32 sqm",
  // },
  // {
  //   image: "path/to/image15.jpg",
  //   roomtype: "Standard",
  //   price: "$105",
  //   PromotionPrice: "$85",
  //   Guest: 1,
  //   bedtype: "Single bed",
  //   Roomsize: "25 sqm",
  // },
  // {
  //   image: "path/to/image16.jpg",
  //   roomtype: "Standard",
  //   price: "$115",
  //   PromotionPrice: "$95",
  //   Guest: 2,
  //   bedtype: "Double bed",
  //   Roomsize: "27 sqm",
  // },
  // {
  //   image: "path/to/image17.jpg",
  //   roomtype: "Suite",
  //   price: "$220",
  //   PromotionPrice: "$200",
  //   Guest: 4,
  //   bedtype: "King bed",
  //   Roomsize: "50 sqm",
  // },
  // {
  //   image: "path/to/image18.jpg",
  //   roomtype: "Suite",
  //   price: "$240",
  //   PromotionPrice: "$220",
  //   Guest: 4,
  //   bedtype: "King bed",
  //   Roomsize: "55 sqm",
  // },
  // {
  //   image: "path/to/image19.jpg",
  //   roomtype: "Deluxe",
  //   price: "$160",
  //   PromotionPrice: "$130",
  //   Guest: 2,
  //   bedtype: "Single bed",
  //   Roomsize: "30 sqm",
  // },
  // {
  //   image: "path/to/image20.jpg",
  //   roomtype: "Deluxe",
  //   price: "$170",
  //   PromotionPrice: "$140",
  //   Guest: 2,
  //   bedtype: "Double bed",
  //   Roomsize: "32 sqm",
  // },
];

export { columns, users };
 